//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elwark.Education.Web.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorManager {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorManager() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Elwark.Education.Web.Resources.ErrorManager", typeof(ErrorManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        internal static string NotFound_NotFount {
            get {
                return ResourceManager.GetString("NotFound:NotFount", resourceCulture);
            }
        }
        
        internal static string UserRestriction {
            get {
                return ResourceManager.GetString("UserRestriction", resourceCulture);
            }
        }
        
        internal static string UserRestriction_PremiumSubscriptionRequired {
            get {
                return ResourceManager.GetString("UserRestriction:PremiumSubscriptionRequired", resourceCulture);
            }
        }
        
        internal static string UserRestriction_CreatedMaximumCurrentTests {
            get {
                return ResourceManager.GetString("UserRestriction:CreatedMaximumCurrentTests", resourceCulture);
            }
        }
        
        internal static string UserRestriction_CreatedMaximumTests {
            get {
                return ResourceManager.GetString("UserRestriction:CreatedMaximumTests", resourceCulture);
            }
        }
        
        internal static string UserRestriction_ReachedMaximumAnswerAttempts {
            get {
                return ResourceManager.GetString("UserRestriction:ReachedMaximumAnswerAttempts", resourceCulture);
            }
        }
        
        internal static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        internal static string GoToHomepage {
            get {
                return ResourceManager.GetString("GoToHomepage", resourceCulture);
            }
        }
        
        internal static string ReloadPage {
            get {
                return ResourceManager.GetString("ReloadPage", resourceCulture);
            }
        }
        
        internal static string Internal_Rpc {
            get {
                return ResourceManager.GetString("Internal:Rpc", resourceCulture);
            }
        }
    }
}
