version: '3.9'

services:

  education.web:
    image: elwark/education/web:${TAG:-latest}
    container_name: "education_web"
    mem_limit: 64M
    mem_reservation: 32M
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "5010:80"
