version: '3.9'

services:
  education.server:
    container_name: "education_web"
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - HTTP_PORTS=80
    ports:
      - "5010:80"
