version: '3.9'

services:

  education.web:
    image: elwark/education/web:${TAG:-latest}
    container_name: "education_web"
    build:
      context: .
      dockerfile: src/Education.Web.Client/Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "5010:80"
